### ISSUE TITLE
Can't delete device

### ISSUE THREAD

**Issue by sinkingfeeling** [kuyio/konnect#1]
Just got Konnect up and running on Azure Virtual Machine, run in to one snag - I can't delete a device. Next to the edit button is an ellipsis and I can see in the html there's supposed to be a dropdown menu but I can't activate it. Help!

**Comment by nicbet** [comment]
@sinkingfeeling Can you please upgrade to Konnect™ 2307.1 and see if the problem is fixed?

```
docker pull ghcr.io/kuyio/konnect:2307.1
```

or 

```
docker pull ghcr.io/kuyio/konnect:latest
```

and then

```
docker-compose up -d
```
