### ISSUE TITLE
docker-compose: line 1: Not: command not found

### ISSUE THREAD

**Issue by strixy** [kuyio/konnect#2]
Following the instructions from here https://konnect.kuy.io/documentation/quickstart 

I spun up a new VPS / Droplet on Digital ocean, but when trying to start the docker container I get the following error. `docker-compose: line 1: Not: command not found`

```
cd /opt/konnect
docker-compose up -d
/usr/local/bin/docker-compose: line 1: Not: command not found
```
Ubuntu version 20.04

Any advice on how to continue?

**Comment by nicbet** [comment]
Hi @strixy, 

this error usually originates from an outdated `docker-compose` version. You can try downloading and installing the latest `docker-compose` binary in your system:

```sh
sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
```

See https://github.com/docker/compose/issues/6268

**Comment by strixy** [comment]
I appreciate that you've provided a fix, but the bug in your code still exists. I'm sorry to have to open a closed ticket, but this is actually a bug report not a support request. I actually don't want or need support as I've decided not to use Kuyio Konnect. I hope you'll understand then that there is little motivation on my part to test a fix for a bug in a product that I don't use. I hope you'll also understand that I'm only following up to help highlight that you do have a bug. I'll show where it is, but there are number of ways you could chose to go about fixing it.

The outdated version that I have "in my system" comes from your install script found here:

https://raw.githubusercontent.com/kuyio/konnect/main/konnect-quickstart-ubuntu.sh

I found this script while following the official documentation found here https://konnect.kuy.io/documentation/quickstart

If you review the documentation and the install script referenced you'll notice that this is not a case of "in my system". I used the recommended system and followed the process as outlined in the docs. That means my system is your system.

If your solution above is correct then the code containing the root source of the bug could be the curl command in the block below. Note the incorrect hard coded version number? If your solution is correct, then this could be the source of the bug. I'm not sure if there is a way for you to make that version number a variable or to just use 'current'? I don't know if you need to edit the docs to make it clear that the end user is responsible for editing the code in the script to reflect the most current version? There are several ways you could go about fixing the issue. Prompt for version number perhaps? I'm just trying to let you know that you have a bug and that new users aren't able to follow the process as outlined in your docs.

```
if ! command -v docker-compose &> /dev/null
then
  echo "Docker Compose not found on the system, installing ..."
  curl -L "https://github.com/docker/compose/releases/download/2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
else
  echo "Docker Compose is present on this system, skipping installation."
fi
```

**Comment by nicbet** [comment]
@strixy Apologies for the confusion. You are absolutely right, there was an issue with the `install-docker.sh` and `konnect-quickstart-ubuntu.sh` scripts, Docker upstream changed their download locations to include a `v` in front of the version tag. 

The scripts in this repository have been updated accordingly. Thanks again for taking the time to provide such a detailed reply!
